[physics]
particle = "Protons"
problem = "matfromCT"
model = "FP" 
OmegaMin = 180
eKin = 80

[numerics]
nx = 23
ny = 23
nz = 73
nMoments = 19
order = 2
solverName = "Tracer_fullPnInEnergy_FP" 
tracerFileName = "FP_E80_BoxInsert_res1mm_corrected"
cfl = 50

[computation]
trace = false
disableGPU = true
