[physics]
particle = "Protons"
problem = "SingleBeam"
model = "FP" 
OmegaMin = 180
eKin = 90

[numerics]
nx = 23
ny = 23
nz = 73
nMoments = 19
order = 2
solverName = "Tracer_rankAdaptiveInEnergy_FP" 
tracerFileName = "FP_E90_res1mm_corrected"
cfl = 50

[computation]
trace = false
disableGPU = true
