[physics]
particle = "Protons"
problem = "BoxInsert"
model = "FP" 
OmegaMin = 180
eKin = 80

[numerics]
nx = 23
ny = 23
nz = 73                                                                                                                                                                                                                                                                                                                                                                                                                                            
nMoments  = 19
order = 2
rank = 100
maxRank = 100
solverName = "Tracer_rankAdaptiveInEnergy_FP" 
tracerFileName = "FP_E80_BoxInsert_res1mm_corrected"
cfl = 20
tolerance = 0.01

[computation]
trace = false
disableGPU = false


