[physics]
particle = "Protons"
problem = "BoxInsert"
model = "Boltzmann" 
OmegaMin = 0
eKin = 80

[numerics]
nx = 23
ny = 23
nz = 73
nMoments = 75
order = 2
solverName = "Tracer_fullPnInEnergy" 
tracerFileName = "Boltzmann_E80_res1mm_BoxInsert"
cfl = 50

[computation]
trace = false
disableGPU = true
