[physics]
particle = "Protons"
problem = "SingleBeam"
model = "Boltzmann" 
OmegaMin = 0
eKin = 90

[numerics]
nx = 23
ny = 23
nz = 73
nMoments = 75
order = 2
solverName = "Tracer_rankAdaptiveInEnergy" 
tracerFileName = "Boltzmann_E90_res1mm"
cfl = 50

[computation]
trace = false
disableGPU = true
